const mobile = [
	{
		Brand: "BLU",
		ModelName: "BLU Life One XL",
		Os: "Android 4.4.2, up to 5.0",
		Release: "2015",
	},
	{
		Brand: "alcatel",
		ModelName: "alcatel 3v",
		Os: "Android 8.0",
		Release: "2018",
	},
	{
		Brand: "Nokia",
		ModelName: "Nokia 8",
		Os: "Android 7.1.1, up to Android 9.0",
		Release: "2017",
	},
	{
		Brand: "Nokia",
		ModelName: "Nokia Asha 308",
		Os: "Feature phone",
		Release: "2012",
	},
	{
		Brand: "Sony",
		ModelName: "Sony Xperia X",
		Os: "Android 6.0.1, up to Android 8.0",
		Release: "2016",
	},
	{
		Brand: "NEC",
		ModelName: "NEC N200",
		Os: "Feature phone",
		Release: "2005",
	},
	{
		Brand: "Prestigio",
		ModelName: "Prestigio MultiPhone 3540 Duo",
		Os: "Android 4.1",
		Release: "2013",
	},
	{
		Brand: "Icemobile",
		ModelName: "Icemobile Shine",
		Os: "Android 2.2",
		Release: "2011",
	},
	{
		Brand: "Celkon",
		ModelName: "Celkon C227",
		Os: "Feature phone",
		Release: "2011",
	},
	{
		Brand: "O2",
		ModelName: "O2 XDA Orion",
		Os: "Microsoft Windows Mobile 5.0 Smartphone",
		Release: "2005",
	},
	{
		Brand: "BQ",
		ModelName: "BQ Aquaris VS",
		Os: "Android 7.1.2, up to Android 8.0",
		Release: "2018",
	},
	{
		Brand: "Realme",
		ModelName: "Realme 6i",
		Os: "Android 10, Realme UI",
		Release: "2020",
	},
	{
		Brand: "Sony",
		ModelName: "Sony Xperia Z3 Compact",
		Os: "Android 4.4.4, up to 6.0",
		Release: "2014",
	},
	{
		Brand: "LG",
		ModelName: "LG KP270",
		Os: "Feature phone",
		Release: "2008",
	},
	{
		Brand: "Samsung",
		ModelName: "Samsung Galaxy Tab 4 10.1",
		Os: "Android 4.4.2, TouchWiz UX UI",
		Release: "2014",
	},
	{
		Brand: "alcatel",
		ModelName: "alcatel Pixi 4 Plus Power",
		Os: "Android 6.0",
		Release: "2016",
	},
	{
		Brand: "Samsung",
		ModelName: "Samsung Galaxy A8",
		Os: "Android 5.1.1, up to 6.0",
		Release: "2015",
	},
	{
		Brand: "Vodafone",
		ModelName: "Vodafone 1231",
		Os: "Microsoft Windows Mobile 6.1 Standard",
		Release: "2009",
	},
	{
		Brand: "Samsung",
		ModelName: "Samsung I6210",
		Os: "Feature phone",
		Release: "2009",
	},
	{
		Brand: "XOLO",
		ModelName: "XOLO Era 2",
		Os: "Android 6.0",
		Release: "2016",
	},
	{
		Brand: "Ericsson",
		ModelName: "Ericsson GF 788e",
		Os: "Feature phone",
		Release: "1997",
	},
	{
		Brand: "Samsung",
		ModelName: "Samsung I9230 Galaxy Golden",
		Os: "Android 4.2",
		Release: "2013",
	},
	{
		Brand: "Apple",
		ModelName: "Apple iPad Air",
		Os: "iOS 7, up to iPadOS 12.4.6",
		Release: "2013",
	},
	{
		Brand: "Gionee",
		ModelName: "Gionee Marathon M4",
		Os: "Android 5, Amigo 3",
		Release: "2015",
	},
	{
		Brand: "LG",
		ModelName: "LG US760 Genesis",
		Os: "Android 2.2",
		Release: "2011",
	},
	{
		Brand: "Karbonn",
		ModelName: "Karbonn A10",
		Os: "Android 4.1",
		Release: "2013",
	},
	{
		Brand: "LG",
		ModelName: "LG E900 Optimus 7",
		Os: "Microsoft Windows Phone 7, up to 7.8",
		Release: "2010",
	},
	{
		Brand: "YU",
		ModelName: "YU Yunique Plus",
		Os: "Android 5.1.1",
		Release: "2016",
	},
	{
		Brand: "Spice",
		ModelName: "Spice Smart Flo 358 (Mi-358)",
		Os: "Android 4.4.2",
		Release: "2014",
	},
	{
		Brand: "Oppo",
		ModelName: "Oppo U3",
		Os: "Android 4.4.4, ColorOS 2",
		Release: "2015",
	},
	{
		Brand: "LG",
		ModelName: "LG BL20 New Chocolate",
		Os: "Feature phone",
		Release: "2009",
	},
	{
		Brand: "Samsung",
		ModelName: "Samsung Galaxy J7 (2016)",
		Os: "Android 6.0.1, up to Android 8.1",
		Release: "2016",
	},
	{
		Brand: "Unnecto",
		ModelName: "Unnecto Edge",
		Os: "Feature phone",
		Release: "2011",
	},
	{
		Brand: "LG",
		ModelName: "LG U300",
		Os: "Feature phone",
		Release: "2006",
	},
	{
		Brand: "LG",
		ModelName: "LG Escape P870",
		Os: "Android 4.0.4",
		Release: "2012",
	},
	{
		Brand: "Micromax",
		ModelName: "Micromax M2",
		Os: "Feature phone",
		Release: "2011",
	},
	{
		Brand: "BLU",
		ModelName: "BLU Amour",
		Os: "Android 4.0",
		Release: "2013",
	},
	{
		Brand: "NEC",
		ModelName: "NEC N940",
		Os: "Feature phone",
		Release: "2004",
	},
	{
		Brand: "Micromax",
		ModelName: "Micromax Canvas Unite 4",
		Os: "Android 6.0",
		Release: "2016",
	},
	{
		Brand: "LG",
		ModelName: "LG K41S",
		Os: "Android 9.0",
		Release: "2020",
	},
	{
		Brand: "OnePlus",
		ModelName: "OnePlus Nord N100",
		Os: "Android 10, OxygenOS 10.5.9",
		Release: "2020",
	},
	{
		Brand: "HTC",
		ModelName: "HTC Desire 400 dual sim",
		Os: "Android OS, Sense UI",
		Release: "2012",
	},
	{
		Brand: "Qtek",
		ModelName: "Qtek 8080",
		Os: "Microsoft Windows Mobile 2003 Smartphone",
		Release: "2004",
	},
	{
		Brand: "Siemens",
		ModelName: "Siemens PenPhone",
		Os: "Feature phone",
		Release: "2001",
	},
	{
		Brand: "Samsung",
		ModelName: "Samsung U100",
		Os: "Feature phone",
		Release: "2007",
	},
	{
		Brand: "HTC",
		ModelName: "HTC Desire 20 Pro",
		Os: "Android 10",
		Release: "2020",
	},
	{
		Brand: "Plum",
		ModelName: "Plum Genius",
		Os: "Feature phone",
		Release: "2011",
	},
	{
		Brand: "Vodafone",
		ModelName: "Vodafone 227",
		Os: "Feature phone",
		Release: "2007",
	},
	{
		Brand: "Sonim",
		ModelName: "Sonim XP1",
		Os: "Feature phone",
		Release: "2007",
	},
	{
		Brand: "Philips",
		ModelName: "Philips 636",
		Os: "Feature phone",
		Release: "2004",
	},
];

export default mobile;
